version: '3.7'
# services:
#   syslog-ng:
#     image: balabit/syslog-ng:latest # Use the official syslog-ng image
#     ports:
#       - "514:514/udp" # Map UDP port for syslog
#     volumes:
#       - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf # Mount custom config
#     restart: unless-stopped

services:
  syslog-ng:
    image: linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./syslog-ng/config:/config
      - ./syslog-ng/log:/var/log #optional
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
    # networks:
    #   - my-network
    
  my-backend:
    image: edowon0623/catalog-service:syslog
    environment: 
      - spring.datasource.url=jdbc:mariadb://my-db:3306/mydb
      - spring.datasource.password=
    ports:
      - 8088:8088
    depends_on:
      - my-db
    networks:
      - my-network

  my-db:
    platform: linux/amd64 # for apple chip
    image: mariadb:latest
    environment: 
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=mydb
    ports:
      - 13306:3306
    # volumes: 
    #   - /Users/dowonlee_1/Desktop/Work/14.online/docker_examples/docker-compose/data:/var/lib/mysql # shared folder
    networks:
      - my-network

networks:
  my-network:
    external: true